spring:
  application:
    name: day01

  mvc:
    view:
      suffix: .html

  h2:
    console:
      enabled: true
      path: /h2-console
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:/boot/DB
    username: sa
    password: 

mybatis:
  mapper-locations: classpath:mapper/account.xml

server:
  port: 8081

  servlet:
    session:
      tracking-modes: cookie